import Head from "next/head";
import Banner from "components/Banner/Banner";
import NavBar from "components/NavBar/NavBar";
import CardSlider from "components/CardSlider/CardSlider";
import { getPopularVideos, getVideos } from "lib/videos";

import styles from "@/styles/Home.module.css";

export default function Home({ disneyVideos, prodVideos, travelVideos, popularVideos }) {
  return (
    <>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <NavBar userName="herbyosbourne31@gmail.com" />
        <Banner
          videoId="4zH5iYM4wJo"
          title="Clifford the red dog"
          subTitle="a very cute dog"
          imgUrl="/static/reddog.jpg"
        />

        <CardSlider title={"Disney"} videos={disneyVideos} size="large" />
        <CardSlider title={"Travel"} videos={travelVideos} size="small" />
        <CardSlider title={"Productivity"} videos={prodVideos} size="medium" />
        <CardSlider title={"Popular"} videos={popularVideos} size="small" />
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const disneyVideos = await getVideos("disney trailer");
  const prodVideos = await getVideos("productivity");
  const travelVideos = await getVideos("travel");
  const popularVideos = await getPopularVideos();

  return {
    props: { disneyVideos, prodVideos, travelVideos, popularVideos }
  };
}
