import Head from "next/head";
import Banner from "components/Banner/Banner";
import NavBar from "components/NavBar/NavBar";
import Card from "components/Card/Card";

import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <NavBar userName="herbyosbourne31@gmail.com" />
        <Banner
          title="Clifford the red dog"
          subTitle="a very cute dog"
          imgUrl="/static/reddog.jpg"
        />
        <Card imgUrl="/static/reddog.jpg" size="large" />
        <Card imgUrl="/static/reddog.jpg" size="medium" />
        <Card imgUrl="/static/reddog.jpg" size="small" />
      </main>
    </>
  );
}
